# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxOperator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxOperatr
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxGesture'

  target 'RxOperatorTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest', '~> 4.0'
    pod 'RxBlocking', '~> 4.0'
  end

  target 'RxOperatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
